/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.BarcodeScanResult;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for BarcodeScanApi
 */
@Ignore
public class BarcodeScanApiTest {

    private final BarcodeScanApi api = new BarcodeScanApi();

    
    /**
     * Scan and recognize an image of a barcode
     *
     * Scan an image or photo of a barcode and return the result.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
     */
    @Test
    public void barcodeScanImageTest()  {
        org.springframework.core.io.AbstractResource imageFile = null;
        BarcodeScanResult response = api.barcodeScanImage(imageFile).block();

        // TODO: test validations
    }
    
}
