/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.BarcodeLookupResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for BarcodeLookupApi
 */
@Ignore
public class BarcodeLookupApiTest {

    private final BarcodeLookupApi api = new BarcodeLookupApi();

    
    /**
     * Lookup EAN barcode value, return product data
     *
     * Lookup an input EAN barcode and return key details about the product
     */
    @Test
    public void barcodeLookupEanLookupTest()  {
        String value = null;
        BarcodeLookupResponse response = api.barcodeLookupEanLookup(value).block();

        // TODO: test validations
    }
    
}
