/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import java.io.File;
import com.cloudmersive.client.gac.model.GetImageInfoResult;
import com.cloudmersive.client.gac.model.MultipageImageFormatConversionResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ConvertImageApi
 */
@Ignore
public class ConvertImageApiTest {

    private final ConvertImageApi api = new ConvertImageApi();

    
    /**
     * Get information about an image
     *
     * Get details from an image such as size, format and MIME type, compression, EXIF data such as location, DPI, unique colors, transparency information, and more
     */
    @Test
    public void convertImageGetImageInfoTest()  {
        org.springframework.core.io.AbstractResource inputFile = null;
        GetImageInfoResult response = api.convertImageGetImageInfo(inputFile).block();

        // TODO: test validations
    }
    
    /**
     * Image format conversion
     *
     * Convert between over 100 file formats, including key formats such as Photoshop (PSD), PNG, JPG, GIF, NEF, and BMP.
     */
    @Test
    public void convertImageImageFormatConvertTest()  {
        String format1 = null;
        String format2 = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        byte[] response = api.convertImageImageFormatConvert(format1, format2, inputFile).block();

        // TODO: test validations
    }
    
    /**
     * Change image DPI
     *
     * Resize an image to have a different DPI
     */
    @Test
    public void convertImageImageSetDPITest()  {
        Integer dpi = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        byte[] response = api.convertImageImageSetDPI(dpi, inputFile).block();

        // TODO: test validations
    }
    
    /**
     * Multi-page image format conversion
     *
     * Convert between over 100 file formats, including support for Multiple-Page formats (e.g. PDFs, TIFFs, etc. with multiple pages).
     */
    @Test
    public void convertImageMultipageImageFormatConvertTest()  {
        String format1 = null;
        String format2 = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        MultipageImageFormatConversionResult response = api.convertImageMultipageImageFormatConvert(format1, format2, inputFile).block();

        // TODO: test validations
    }
    
}
