/*
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.ExtractEntitiesRequest;
import com.cloudmersive.client.gac.model.ExtractEntitiesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ExtractEntitiesApi
 */
@Ignore
public class ExtractEntitiesApiTest {

    private final ExtractEntitiesApi api = new ExtractEntitiesApi();

    
    /**
     * Extract entities from string
     *
     * Extract the named entitites from an input string.
     */
    @Test
    public void extractEntitiesPostTest()  {
        ExtractEntitiesRequest value = null;
        ExtractEntitiesResponse response = api.extractEntitiesPost(value).block();

        // TODO: test validations
    }
    
}
