/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.DominantColorResult;
import java.io.File;
import com.cloudmersive.client.gac.model.ImageMetadata;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for InfoApi
 */
@Ignore
public class InfoApiTest {

    private final InfoApi api = new InfoApi();

    
    /**
     * Returns the dominant colors of the image
     *
     * Uses advanced image processing to extract the top 5 dominant colors in the image, returned in the order of dominance with the most-dominant color first.  These are the primary perceptual colors used in the image as perceived by a viewer.
     */
    @Test
    public void infoGetDominantColorTest()  {
        org.springframework.core.io.AbstractResource imageFile = null;
        DominantColorResult response = api.infoGetDominantColor(imageFile).block();

        // TODO: test validations
    }
    
    /**
     * Returns the image metadata including EXIF and resolution
     *
     * Returns the metadata information on the image, including file type, EXIF (if available), and resolution.
     */
    @Test
    public void infoGetMetadataTest()  {
        org.springframework.core.io.AbstractResource imageFile = null;
        ImageMetadata response = api.infoGetMetadata(imageFile).block();

        // TODO: test validations
    }
    
}
