/*
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.HttpOrchestrationRequest;
import com.cloudmersive.client.gac.model.HttpOrchestrationResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for OrchestratorApi
 */
@Ignore
public class OrchestratorApiTest {

    private final OrchestratorApi api = new OrchestratorApi();

    
    /**
     * Orchestrate multiple HTTP API calls with a single API call in the order specified.  Call other Cloudmersive APIs or third party APIs.  For Cloudmersive APIs, the API Key will automatically propogate to the child calls without needing to be set explicitly.  Name each task and reference the output of a previous task in the inputs to a given task.
     *
     * 
     */
    @Test
    public void orchestratorHttpSimpleTest()  {
        HttpOrchestrationRequest request = null;
        HttpOrchestrationResponse response = api.orchestratorHttpSimple(request).block();

        // TODO: test validations
    }
    
}
