/*
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.ParseRequest;
import com.cloudmersive.client.gac.model.ParseResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ParseApi
 */
@Ignore
public class ParseApiTest {

    private final ParseApi api = new ParseApi();

    
    /**
     * Parse string to syntax tree
     *
     * Parses the input string into a Penn Treebank syntax tree
     */
    @Test
    public void parseParseStringTest()  {
        ParseRequest input = null;
        ParseResponse response = api.parseParseString(input).block();

        // TODO: test validations
    }
    
}
