/*
 * nlpapiv2
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.GetWordsRequest;
import com.cloudmersive.client.gac.model.GetWordsResponse;
import com.cloudmersive.client.gac.model.SentenceSegmentationRequest;
import com.cloudmersive.client.gac.model.SentenceSegmentationResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SegmentationApi
 */
@Ignore
public class SegmentationApiTest {

    private final SegmentationApi api = new SegmentationApi();

    
    /**
     * Extract sentences from string
     *
     * Segment an input string into separate sentences, output result as a string.
     */
    @Test
    public void segmentationGetSentencesTest()  {
        SentenceSegmentationRequest input = null;
        SentenceSegmentationResponse response = api.segmentationGetSentences(input).block();

        // TODO: test validations
    }
    
    /**
     * Get words in input string
     *
     * Get the component words in an input string
     */
    @Test
    public void segmentationGetWordsTest()  {
        GetWordsRequest input = null;
        GetWordsResponse response = api.segmentationGetWords(input).block();

        // TODO: test validations
    }
    
}
