/*
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.CreateHandwritingRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for TextGenerationApi
 */
@Ignore
public class TextGenerationApiTest {

    private final TextGenerationApi api = new TextGenerationApi();

    
    /**
     * Create an image of handwriting in PNG format
     *
     * Uses Deep Learning to generate realistic handwriting and returns the result as a PNG image
     */
    @Test
    public void textGenerationCreateHandwritingPngTest()  {
        CreateHandwritingRequest request = null;
        Object response = api.textGenerationCreateHandwritingPng(request).block();

        // TODO: test validations
    }
    
}
