/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.DocumentTransformEditSession;
import com.cloudmersive.client.gac.model.DocxTableTableFillMultiRequest;
import com.cloudmersive.client.gac.model.DocxTableTableFillRequest;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for TransformDocumentApi
 */
@Ignore
public class TransformDocumentApiTest {

    private final TransformDocumentApi api = new TransformDocumentApi();

    
    /**
     * Replace string in Word DOCX document, return result
     *
     * Replace all instances of a string in an Office Word Document (docx)
     */
    @Test
    public void transformDocumentDocxReplaceTest()  {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        byte[] response = api.transformDocumentDocxReplace(matchString, replaceString, inputFileUrl, matchCase, inputFile).block();

        // TODO: test validations
    }
    
    /**
     * Replace string in Word DOCX document, return edit session
     *
     * Replace all instances of a string in an Office Word Document (docx).  Returns an edit session URL so that you can chain together multiple edit operations without having to send the entire document contents back and forth multiple times.  Call the Finish Editing API to retrieve the final document once editing is complete.
     */
    @Test
    public void transformDocumentDocxReplaceEditSessionTest()  {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        DocumentTransformEditSession response = api.transformDocumentDocxReplaceEditSession(matchString, replaceString, inputFileUrl, matchCase, inputFile).block();

        // TODO: test validations
    }
    
    /**
     * Fill in data in a table in a Word DOCX document, return result
     *
     * Replace placeholder rows ina  table in an Office Word Document (docx) using one or more templates
     */
    @Test
    public void transformDocumentDocxTableFillInTest()  {
        DocxTableTableFillRequest request = null;
        byte[] response = api.transformDocumentDocxTableFillIn(request).block();

        // TODO: test validations
    }
    
    /**
     * Fill in data in a table in a Word DOCX document, return edit session
     *
     * Replace placeholder rows ina  table in an Office Word Document (docx) using one or more templates.  Returns an edit session URL so that you can chain together multiple edit operations without having to send the entire document contents back and forth multiple times.  Call the Finish Editing API to retrieve the final document once editing is complete.
     */
    @Test
    public void transformDocumentDocxTableFillInEditSessionTest()  {
        DocxTableTableFillRequest request = null;
        DocumentTransformEditSession response = api.transformDocumentDocxTableFillInEditSession(request).block();

        // TODO: test validations
    }
    
    /**
     * Fill in data in multiple tables in a Word DOCX document, return result
     *
     * Replace placeholder rows in multiple tables in an Office Word Document (docx) using one or more templates
     */
    @Test
    public void transformDocumentDocxTableFillInMultiTest()  {
        DocxTableTableFillMultiRequest request = null;
        byte[] response = api.transformDocumentDocxTableFillInMulti(request).block();

        // TODO: test validations
    }
    
    /**
     * Replace string in PowerPoint PPTX presentation, return result
     *
     * Replace all instances of a string in an Office PowerPoint Document (pptx)
     */
    @Test
    public void transformDocumentPptxReplaceTest()  {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        org.springframework.core.io.AbstractResource inputFile = null;
        byte[] response = api.transformDocumentPptxReplace(matchString, replaceString, inputFileUrl, matchCase, inputFile).block();

        // TODO: test validations
    }
    
}
