/*
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.UserAgentValidateRequest;
import com.cloudmersive.client.gac.model.UserAgentValidateResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for UserAgentApi
 */
@Ignore
public class UserAgentApiTest {

    private final UserAgentApi api = new UserAgentApi();

    
    /**
     * Parse an HTTP User-Agent string, identify robots
     *
     * Uses a parsing system and database to parse the User-Agent into its structured component parts, such as Browser, Browser Version, Browser Engine, Operating System, and importantly, Robot identification.
     */
    @Test
    public void userAgentParseTest()  {
        UserAgentValidateRequest request = null;
        UserAgentValidateResponse response = api.userAgentParse(request).block();

        // TODO: test validations
    }
    
}
